# Tip and Tricks for NUMPY


In [62]:
import numpy as np
from time import perf_counter_ns
print(f"Numpy Version : {np.__version__}")

Numpy Version : 1.23.2


## 1. np datatype

In [9]:
def get_info(a):
    print(f"array: {a}")
    print(f"Shape of array: {a.shape}")
    print(f"Data type of array: {a.dtype}")
    print(f"Dimension of array: {a.ndim}")
    print(f"Size of array: {a.size}")
    print(f"Itemsize of array: {a.itemsize}")

a = np.array([1, 2 ,3])
b = np.array([[1,2,3], [2,3,4]])
get_info(b)


array: [[1 2 3]
 [2 3 4]]
Shape of array: (2, 3)
Data type of array: int64
Dimension of array: 2
Size of array: 6
Itemsize of array: 8


In [10]:
#np arrays are muttable

## Difference between python list and numpy array


In [169]:
python_list = [1,2,3]
np_array = np.array([1, 2, 3])
print(python_list)
print(np_array)

[1, 2, 3]
[1 2 3]


### Appending

In [177]:
# python_list = [1, 2, 3]
# np_array = np.array([1, 2, 3])
#
# Python list appending
python_list.append(4)  # Mutates the actual python_list

# np array list appending 
new_np_array = np.append(np_array, np.array([4]))  # Does not mutate the actual np_array
# Concatenate
new_np_array = np.concatenate((np_array, np_array), axis = 0)
# hstack
new_np_array = np.hstack((np.array([1, 2, 3, 4]), np.array([5, 6, 7, ])))  # Dimensions must match
new_np_array = np.vstack((np.array([1, 2, 3, 4]), np.array([1, 2, 3, 4])))
print(new_np_array)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### Arithimetic Operation

In [36]:
# python_list = [1, 2, 3, 4]
# np_array = np.array([1, 2, 3, 4])
#
# Python List

python_list = python_list + [5]  # result [1, 2, 3, 4]
python_list += [6]  # result [1, 2, 3, 4, 5]
python_list *= 2  # result [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


# arithimetic operation of np array
np_array + np.array([5]) # result [6, 7, 8]
np_array * 2  # result [2, 4, 5]

array([20, 24, 28,  8])

## Dot Product

In [44]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]
a1 = np.array(l1)
a2 = np.array(l2)

In [89]:
# Python list dot product
def dot_prod(l1, l2):
    sum = 0
    for x, y in zip(l1, l2):
        sum += x * y
    return sum
t0_start = perf_counter_ns()
dot_prod(l1, l2)
t0_end = perf_counter_ns()

# np array dot product
# Method 1 
t1_start = perf_counter_ns()
dot = np.dot(a1, a2)
t1_end = perf_counter_ns()

# Method 2 
t2_start = perf_counter_ns()
dot = np.sum(a1 * a2)
t2_end = perf_counter_ns()

# Method 3 
t3_start = perf_counter_ns()
dot = (a1 * a2).sum()
t3_end = perf_counter_ns()

# Method 4
t4_start = perf_counter_ns()
dot = a1 @ a2
t4_end = perf_counter_ns()

print(f"{t0_end - t0_start:,}")
print(f"{t1_end - t1_start:,}")
print(f"{t2_end - t2_start:,}")
print(f"{t3_end - t3_start:,}")
print(f"{t4_end - t4_start:,}")



56,836
80,542
91,737
55,045
48,522


## N dimension array

In [148]:
np_array = np.array([[1, 2, 3], [3, 4, 5]])
print(np_array)
np_array.shape  # result (2, 3) (row, column)
# Slicing
np_array[0]  # result [1, 2, 3]
np_array[:, 0]  # result [1, 3]
np_array[0, :]  # result [1, 2, 3]

np_array = np.array([[1, 2], [3, 4]])

# Transpose
np_array.T
# Matrix Invsere
np.linalg.inv(np_array)
# Matrix determinant
np.linalg.det(np_array)
# Diagonal Matrix diag function overloaded
np.diag(np_array)
#
np.diag(np.diag(np_array))

[[1 2 3]
 [3 4 5]]


array([[1, 0],
       [0, 4]])

In [149]:
# Python List
ll = [[1, 2], [3, 4]]
ll[0][0]

1

In [157]:
# Boolean index
print(f"{np_array[np_array > 2]}")
print(f"{np.where(np_array > 2, np_array, -1)}")  # Keep N dimension shape and if not greater than 2 return -1
#
even = np.argwhere(np_array % 2 == 0)
np_array[even]


[3 4]
[[-1 -1]
 [ 3  4]]


In [121]:
np_array[0, [0, 2]]

array([1, 3])

## Creating & reshapping Arrays

In [168]:
np_array = np.arange(1, 7)
print(np_array)
print(np_array.shape)
print(np_array.reshape(2, 3))

b = np_array[np.newaxis, :]
print(b.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(1, 6)


## Broadcasting

## Functions and Axis

In [185]:
a = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

# optional parameter axis = {0, 1, none} if 0 for each column, if 1 for each row, if none total
a.sum(axis = 0)  
a.mean(axis = 0)
a.std(axis = 0) 
np.std(a, axis = 0)
np.min(a, axis = 1)
np.max(a, axis = 0)

array([ 5, 10])

In [186]:
a = np.array([1, 2, 3])
b = a.copy()
b[3] = 2
print(a)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [196]:
## Generating Arrays
print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2,3), -1))
print(np.eye(3))
print(np.arange(1, 10, 2)) 
print(np.linspace(1, 10, 5))  # Create equally spaced array, last argument number of elements


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [188]:
python_list = [1, 2, 3]
python_list[2] = 2
python_list

[1, 2, 2]

## Random

In [211]:
print(np.random.random(size=(3, 2)))
print(np.random.randn(2, 3))  # normal/Guassian dimension
print(np.random.randint(low=1, high=10, size=(3, 3)))
print(np.random.choice(a=[1, 2, 3], size=10))
print(np.random.choice(a=3, size=10))

[[0.17634753 0.56184835]
 [0.38302497 0.4467518 ]
 [0.31701715 0.63104003]]
[[-1.69488354  2.22412867 -0.18834831]
 [ 0.9638267  -0.7018579   1.36462679]]
[[4 2 7]
 [5 9 4]
 [9 4 6]]
[2 2 1 1 1 1 1 2 3 3]
[0 0 1 1 0 1 1 1 0 0]


In [212]:
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)
# compare value
lhand = 0
rhand = 0
np.allclose(lhand, rhand)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [ ]:
np.linalg.inv(A).dot(b)

# Method 2 Preferred
np.linalg.solve(A, b)


Source:

https://www.youtube.com/watch?v=9JUAPgtkKpI&ab_channel=PythonEngineer